### PR TITLE
fix: avatar disappear

### LINKED ISSUE #66: Disappearance of Avatar
It seems that the avatar will disappear sometimes

image

### LINKED ISSUE #68: Add some transformation after clicking "submit"
在設定完個人頁面資訊後按下submit，畫面不會有任何變化，對使用者而言很難確定是否真的成功更新資訊，而必須跳回<個人頁面>查詢才能得知，如果在按下submit按鈕後加一些畫面上的變化或許能幫助使用者了解當前狀態
- 或許可以直接跳回<個人頁面>，使用者也能立刻得知成功新與否

### PR DESCRIPTION
**Pull request by JacobLinCool**
resolve #66 
resolve #68 

It seems that we may update the avatar with empty string when editing other fields.

### CODE REVIEW

**Review by skyhong2002 — APPROVED** [review]
Great job!
不過我沒有在自己的機器跑 就再說

**Comment by skyhong2002** [comment]
可能 @April-Aries 會有興趣看

File: src/routes/api/auth/self/+server.ts [hunk 1]
```diff
@@ -68,29 +68,30 @@ export const PUT: RequestHandler = async ({ request, locals }) => {
...
-		);
+		if (payload.avatar.length > 8 * 1024 * 1024) {
+			throw new Error();
+		}
+		if (payload.avatar.length > 64) {
+			avatar_id = await upload_avatar(
+				locals.crystal.username,
+				Buffer.from(payload.avatar, "base64"),
+			);
+		}
```
Comment (Bogay) [inline src/routes/api/auth/self/+server.ts:79]: maybe we can use zod schema to enforce this constraint?

Comment (Bogay) [inline src/routes/api/auth/self/+server.ts:79]: If the avatar is not uploaded, maybe we should throw an error? so that it's more clear what happened.

File: src/routes/settings/profile/+page.svelte [hunk 2]
```diff
@@ -15,31 +16,45 @@
...
-				byteString += String.fromCharCode(b);
-			}
-			encodedAvatar = window.btoa(byteString);
+		if (updating) {
+			return;
 		}
+		updating = true;
+
+		try {
+			let encodedAvatar = "";
```
Comment (Bogay) [inline src/routes/settings/profile/+page.svelte:27]: I forgot that I should name it `encoded_avatar`, also, `byte_string` below.

Comment (JacobLinCool) [reply src/routes/settings/profile/+page.svelte:27]: That's fine, I believe it'll be fix in the future refactoring (if any) about this part.

File: src/routes/api/auth/self/+server.ts (hunk 1 above)
Comment (JacobLinCool) [reply src/routes/api/auth/self/+server.ts:79]: Yes, that's a good idea, but I would like to allow empty (or optional) field to reduce the payload size if we are not going to update the avatar.

Comment (JacobLinCool) [reply src/routes/api/auth/self/+server.ts:79]: Good point! I am considering using `sveltekit-superform` (it use `zod` to perform validation under the hood, which can be run on both-side) to improve the data mutating process.
